# my github actions workflow file for running a bandit security scan
# using this to automatically check my code for common python security issues

name: Bandit Security Scan

# scan to run every time i push to main or open a pull request to main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  bandit-scan:
    # the scan will run in a clean ubuntu environment provided by github
    runs-on: ubuntu-latest

    steps:
    # check out my code so the workflow has access to it
    - name: checkout code
      uses: actions/checkout@v3

    # set up python because bandit is a python tool
    - name: set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # using the same version as my local project

    # install bandit using pip so i can run it in the next step
    # making sure pip is the latest version
    # installing bandit for security scanning
    - name: install bandit
      run: |
        python -m pip install --upgrade pip  
        pip install bandit  

    # finally i run bandit on the key folders of my django project
    - name: run bandit scan
      run: bandit -r budgets users team_budget_planner  # -r to scan all files inside these folders
